dist: trusty
language: php

php:
- 7.4
- 8.0
- nightly

matrix:
    allow_failures:
    - php: nightly

## Cache composer
cache:
    directories:
    - $HOME/.composer/cache

before_script:
- pecl channel-update pecl.php.net
- printf "\n" | pecl install imagick
- travis_retry composer update --no-interaction --prefer-dist

script:
- vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
